---
title: "A Replication of Study 3 in Stellar et al. (2018): Awe and Humility"
shorttitle: "Replication of Stellar et al. (2018)"
author:
  - name: Tizian M. B. Schuhbeck
    corresponding: true
    orcid: 0009-0005-5903-674X
    email: t.schuhbeck@campus.lmu.de
    affiliations:
      - name: Ludwig-Maximilians-Universität München
        department: Department of Psychology
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
course:  \"Forschungsorientiertes Praktikum I – Grundlagen der Forschung"
professor: Prof. Dr. Felix Schönbrodt
duedate: 16.9.2026
note: |
  Matriculation No.: 11596109
abstract: "As part of the CREP project... we follow a direct replication and extension approach."
impact-statement: "This template helps you get started."
keywords: [Registered Replication, Humility, Awe, Emotion, Self-Concept, CREP, Video Manipulation]
bibliography: bibliography.bib
mask: false
format:
  apaquarto-pdf:
    documentmode: stu
  apaquarto-docx: default
  apaquarto-html: default
word-count: true
---


```{r, echo=FALSE, include=FALSE}

# This manuscript is rendered within its subfolder /manuscript. Therefore we need paths
# relative to the manuscript. "../" means: go one directory up.

source("../0b-preprocessing.R", chdir=TRUE)
source("../1-scales.R", chdir=TRUE)
source("../2-descriptive_stat.R", chdir=TRUE)
source("../3-confirmatory_analyses.R", chdir=TRUE)
source("../4-exploratory_analyses.R", chdir=TRUE)

library(papaja)  # for formatting of APA style t-tests etc.
```






<!-- The introduction should not have a level-1 heading such as Introduction. -->

The seminal findings of the @open2015estimating triggered what is now known as the 'replication crisis' in psychological science, prompting researchers to question thusfar widely unchallenged publications by and large.
Since then, there has been an onging effort within the psychological research community to actively persue replication of affected studies with important findings, aiming to reevaluate their validity and ultimately restore trust in the body of psychological knowledge. 
As part of the Collaborative Replications and Education Project (CREP) project of @grahe2026crep, we aim to contribute to the endeavour descirbed above, investigating the replicability of the results in 'Study 3' of @stellar2018awe: Awe and Humility. 
In this study,  the authors hypothesize momentary experiences of awe to cause a temporary increase in humility. 
The authors operationalize this hypothesis by means of a randomized video intervention, designed to induce either a state of awe or a neutral state, with a subsequent evaluation on a behavioral measure of humility. 
Both theoretical background and original study design are outlined in detail in the original publication of @stellar2018awe. 
To ensure transparency, following the general recommendation of adopting the principles of open science [@schonbrodt2018forschungstransparenz], we have made all relevant materials for this replication study available on the platform Open Science Framework (OSF), in particular the preregistration form at <https://osf.io/537aq>.


## A Direct Replication and Extension of Stellar et al. (2018)

To ensure a direct replication, we aim to adopt the authors orignial methodology and analysis wherever possible. 
As our recruitment of participants has taken place in germany, however, we have opted to translate the study material into german, in particular the audio track for the neutral condition video. 
Our recruitment process follows the snowball sampling principle [@goodman1961snowball], consequently our sample consits of mostly students, as well as their friends and relatives, resulting in demographics distinct from to the original sample of @stellar2018awe. 
All known deviations are documented in their entirety within the preregistration form. 
For the direct replication, we aim to replicate the following hypothesis.

H1: Relative to a neutral control condition, the original awe inducing video increases humility in a behavioral measure.

In addition to our direct replication, we extend our study by the following confirmatory hypothesis, investigated using the same data.

H2: Relative to a neutral control condition, the new awe inducing video increases humility in a behavioral measure.

Furthermore, we extend our study by the following exploratory hypothesis.

E1: The new (more modern) awe inducing video leads to higher awe ratings compared to
the old awe inducing video.

Note, that as documented within the preregistration, we have formulated a list of multiple supplementary exploratory hypotheses. 
Of these, E1 was chosen at random prior to any further data analyses.
The full list of all exploratory hypotheses is documented in the publicly available preregistration form.



# Method

The scripts required for reproducing the following results have been made publicaly available on GitHub at <https://github.com/TiziSchuh/Stellar_Rep_01>.
The hypotheses, operationalizations, analysis plan, inference criteria, and sample size justification have been preregistered at <https://osf.io/537aq>. Open material and data can all be found at [https://osf.io/cy287](https://osf.io/cy287). 

As outlined in the preregistration, the confirmatory hypotheses 

H1: Relative to a neutral control condition, the original awe inducing video increases humility in a behavioral measure.

H2: Relative to a neutral control condition, the new awe inducing video increases humility in a behavioral measure.


Independent Variable (IV): Video condition (Neutral vs. Awe Original vs. Awe Modern).
Dependent Variable (DV): State humility, operationalized as the log-transformed ratio of listed personal strengths to weaknesses. The number of strengths and weaknesses are counted by two independent raters from the free-text answer of the participants in a writing exercise. We use the “Codebook Instructions for Counting Participant-Reported Strengths and Weaknesses” from https://doi.org/10.26443/msurj.v19i1.231 (Appendix B)

The awe emotional state is computed as the mean of three items (Item1: Staunen, Item 2: Faszination, Item 3: Ehrfurcht.)


Furthermore, It should contain one individual (exploratory) analysis, which also is described in the course report.

E1: The new (more modern) awe inducing video leads to higher awe ratings compared to
the old awe inducing video.

## Participants

The initial sample had `r nrow(dat0)` participants. We preregistered to exclude participants who did not write anything in the writing assignment (`r sum(!dat0$has_writing_assignment)` exclusions) or indicated that their data should not be used (`r sum(!dat0$has_agreed)` exclusions), leading to a final sample size of *n* = `r nrow(dat)`. The final sample had a mean age of `r mean(demo$age, na.rm = TRUE) %>% round(1)` (*SD* = `r sd(demo$age, na.rm = TRUE) %>% round(1)`, range: `r min(demo$age, na.rm = TRUE)`--`r max(demo$age, na.rm = TRUE)`).

## Measures

- measure of awe (3 out of 5 items in 7? point likert scale)

- measure of humility (writing excercise, count and transform...)

## Procedure

One-time, cross-sectional online study. Data collection: 19.06.2026 - 10.07.2026.
Participants first watch the video, then do the strength/weakness writing exercise, then
report on their emotional state. Finally they report on the control questions.

## Statistical Procedure

Exclude persons with zero weakness to calculate log. Through log we get more normally distributed data.
For H1 and H2, we perform t-test with a p-value of...


## Deviations from Preregistration

Power not enough bc valid participants?

# Results

## Confirmatory Results

The results was: `r apa_print(t_H1)$full_result`.

## Exploratory Results

The new video... (just as effective on awe measure, effect also non-significant)

# Discussion

## Limitations and Future Directions

lack of evidence is not evidence of absence. Maybe just power not big enough or unlucky... but for this: CREP. Also, we have not tested for MI, explicitely investigating to what extent the translation may have an impact on the reproducability of the effect would adress this limitation. 

## Conclusion

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# This Section Is an Appendix {#apx-a}


# Another Appendix {#apx-b}